version: "3.8"

services:
  app:
    extends:
      file: docker-compose.yaml
      service: app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moonshot-auth.rule=Host(`jswgc4skkssw4wwwg0w4ocwk.a.selfhosted.hackclub.com`)"
      - "traefik.http.routers.moonshot-auth.entrypoints=https"
      - "traefik.http.routers.moonshot-auth.tls=true"
      - "traefik.http.routers.moonshot-auth.tls.certresolver=letsencrypt"
      - "traefik.http.services.moonshot-auth.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
