version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.moonshot.rule=Host(`${CANONICAL_HOST}`)"
        - "traefik.http.routers.moonshot.entrypoints=https"
        - "traefik.http.routers.moonshot.tls=true"
        - "traefik.http.routers.moonshot.tls.certresolver=letsencrypt"
        - "traefik.http.services.moonshot.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M 
