version: "3.8"

services:
  app:
    extends:
      file: docker-compose.yaml
      service: app
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.moonshot-testing.rule=Host(`${CANONICAL_HOST}`)"
        - "traefik.http.routers.moonshot-testing.entrypoints=https"
        - "traefik.http.routers.moonshot-testing.tls=true"
        - "traefik.http.routers.moonshot-testing.tls.certresolver=letsencrypt"
        - "traefik.http.services.moonshot-testing.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://${CANONICAL_HOST}
      - NEXTAUTH_TRUST_HOST=true
