version: "3.8"

services:
  app:
    extends:
      file: docker-compose.yaml
      service: app
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.moonshot-testing.rule=Host(`${CANONICAL_HOST}`)"
        - "traefik.http.routers.moonshot-testing.entrypoints=https"
        - "traefik.http.routers.moonshot-testing.tls=true"
        - "traefik.http.routers.moonshot-testing.tls.certresolver=letsencrypt"
        - "traefik.http.services.moonshot-testing.loadbalancer.server.port=3000"
        # Forward proxy headers so Next/Auth sees the public host and proto
        - "traefik.http.middlewares.moonshot-forward-staging.headers.customrequestheaders.X-Forwarded-Host=${CANONICAL_HOST}"
        - "traefik.http.middlewares.moonshot-forward-staging.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.moonshot-forward-staging.headers.customrequestheaders.X-Forwarded-Port=443"
        # Attach the middleware to the router
        - "traefik.http.routers.moonshot-testing.middlewares=moonshot-forward-staging@docker"
    environment:
      - NODE_ENV=production
